# Generated by Django 3.0.5 on 2020-05-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию блюда(например, супы, салаты, пицца и т.д.', max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назовите блюдо', max_length=200, verbose_name='Навзание блюда')),
                ('price', models.IntegerField(help_text='Укажите цену', verbose_name='Цена блюда')),
                ('image', models.ImageField(default='002.jpg', upload_to='dishes_imgs', verbose_name='Картинка блюда')),
                ('description', models.CharField(help_text='Опишите блюдо', max_length=200, verbose_name='Описание блюда')),
                ('portionWeight', models.IntegerField(help_text='укажите массу порции', verbose_name='Масса порции')),
                ('category', models.ManyToManyField(help_text='Выберите категорию(ии) блюда (для выбора нескольких категорий зажмите клавишу CTRL или Command на MacOS', related_name='dishes', to='catalog.Category')),
            ],
            options={
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ресторана')),
                ('workTime', models.CharField(help_text='укажите ', max_length=200, verbose_name='График работы')),
                ('minOrder', models.IntegerField(help_text='Минимальный заказ', verbose_name='Средний чек')),
                ('freeOrder', models.IntegerField(verbose_name='Бесплатная доставка с суммы заказа от:')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес ресторана')),
                ('delivery', models.IntegerField(verbose_name='Стоимость доставки')),
                ('info', models.CharField(help_text='Информация', max_length=200, verbose_name='Информация о ресторане')),
            ],
            options={
                'verbose_name_plural': 'Ресторан',
            },
        ),
        migrations.CreateModel(
            name='DishExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите дополнительные продукты к блюду', max_length=200, verbose_name='Дополнительно')),
                ('price', models.IntegerField(help_text='укажите цену', verbose_name='Цена')),
                ('active', models.BooleanField(verbose_name='Добавить')),
                ('dish', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='catalog.Dish')),
            ],
            options={
                'verbose_name_plural': 'Дополнительно к блюду',
            },
        ),
        migrations.CreateModel(
            name='DishAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='укажите название', max_length=200, verbose_name='Название добавки')),
                ('addPrice', models.IntegerField(help_text='укажите цену', verbose_name='Цена')),
                ('active', models.BooleanField(verbose_name='Добавить')),
                ('dish', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='catalog.Dish')),
            ],
            options={
                'verbose_name_plural': 'Добавки к блюду',
            },
        ),
    ]
