# Generated by Django 3.0.5 on 2020-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='not_found.jpg', upload_to='dishes_imgs', verbose_name='Картинка блюда'),
        ),
    ]
