# Generated by Django 3.0.5 on 2020-05-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=False, help_text='Выберите категорию(ии) блюда (для выбора нескольких категорий зажмите клавишу CTRL или Command на MacOS', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catalog.Category'),
        ),
    ]
