# Generated by Django 3.0.5 on 2020-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='minOrder',
            field=models.IntegerField(help_text='Минимальный заказ', verbose_name='Минимальный заказ'),
        ),
    ]
