# Generated by Django 3.0.5 on 2020-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverTo',
            field=models.CharField(max_length=255, verbose_name='Доставить к'),
        ),
    ]
