# Generated by Django 3.0.5 on 2020-06-18 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.Разрешено до 14 цифр.", regex='^\\+?1?\\d{9,14}$')], verbose_name='Номер телефона'),
        ),
    ]
