# Generated by Django 3.0.5 on 2020-06-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200618_1625'),
        ('orders', '0002_auto_20200619_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CartItem'),
        ),
    ]
